# Generated by Django 3.1.5 on 2021-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Open', 'Opened'), ('Closed', 'Closed')], default='Open', max_length=6),
        ),
    ]
