# Generated by Django 3.1.5 on 2021-01-31 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='projects_app.project'),
        ),
    ]
