# Generated by Django 3.1.5 on 2021-02-06 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0009_auto_20210206_0908'),
        ('projects_app', '0003_auto_20210131_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='repositories_app.repository'),
        ),
    ]
