language: python
services:
  - postgresql
python:
  - "3.9.1"
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database uks_db;' -U postgres
  - psql -c 'create role uks login superuser password 'uks';' -U postgres
script:
  - python uks_project/manage.py test issues_app projects_app users wiki_app
branches:
  only:
  - main
  - development
