version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=uks_db
      - POSTGRES_USER=uks
      - POSTGRES_PASSWORD=uks
  web:
    build: .
    command: python manage.py runserver
    volumes:
      - .:/uks_project
    ports:
      - "8000:8000"
    depends_on:
      - db

