version: "3.9"
   
services:
  uks_db:
    image: postgres
    
  web:
    container_name: uks_app
    build: .
    command: ["./wait_for_db.sh"]
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - uks_db
    environment:
    - POSTGRES_DB=uks_db
    - POSTGRES_USER=uks
    - POSTGRES_PASSWORD=uks