# Generated by Django 3.1.5 on 2021-02-03 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0001_initial'),
        ('users', '0007_remove_appuser_projects'),
        ('projects_app', '0003_auto_20210131_1956'),
        ('issues_app', '0007_auto_20210201_2054'),
        ('branches_app', '0005_auto_20210131_1925'),
        ('repositories_app', '0002_auto_20210202_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='branches',
            field=models.ManyToManyField(blank=True, related_name='branches', to='branches_app.Branch'),
        ),
        migrations.AddField(
            model_name='repository',
            name='issues',
            field=models.ManyToManyField(blank=True, related_name='issues', to='issues_app.Issue'),
        ),
        migrations.AddField(
            model_name='repository',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', to='issues_app.Label'),
        ),
        migrations.AddField(
            model_name='repository',
            name='milestones',
            field=models.ManyToManyField(blank=True, related_name='milestones', to='issues_app.Milestone'),
        ),
        migrations.AddField(
            model_name='repository',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects_app.Project'),
        ),
        migrations.AddField(
            model_name='repository',
            name='wiki',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wiki', to='wiki_app.wiki'),
        ),
        migrations.CreateModel(
            name='RepositoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Owner', 'Owner'), ('Colaborator', 'Colaborator')], max_length=11)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_user', to='users.appuser')),
            ],
        ),
        migrations.AddField(
            model_name='repository',
            name='repository_users',
            field=models.ManyToManyField(blank=True, related_name='repository_users', to='repositories_app.RepositoryUser'),
        ),
    ]
