# Generated by Django 3.1.5 on 2021-02-03 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories_app', '0003_auto_20210203_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
