# Generated by Django 3.1.5 on 2021-02-04 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0003_auto_20210203_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='milestones',
        ),
    ]
