# Generated by Django 3.1.5 on 2021-02-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0004_auto_20210203_2009'),
        ('repositories_app', '0004_auto_20210204_1315'),
    ]

    operations = [
    ]
