# Generated by Django 3.1.5 on 2021-02-04 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0007_auto_20210204_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositoryuser',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='repositories_app.repository'),
        ),
    ]
