# Generated by Django 3.1.5 on 2021-02-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0009_auto_20210206_1852'),
        ('repositories_app', '0009_auto_20210206_2155'),
        ('repositories_app', '0009_auto_20210206_0908'),
    ]

    operations = [
    ]
