# Generated by Django 3.1.5 on 2021-02-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0010_merge_20210208_1335'),
        ('repositories_app', '0010_merge_20210208_1207'),
    ]

    operations = [
    ]
