# Generated by Django 3.1.5 on 2021-02-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0012_auto_20210214_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(max_length=256)),
            ],
        ),
    ]
