# Generated by Django 3.1.5 on 2021-02-01 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_appuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='data',
            field=models.CharField(default='a', max_length=10),
        ),
    ]
