# Generated by Django 3.1.5 on 2021-02-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_auto_20210131_1956'),
        ('users', '0005_remove_appuser_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='projects',
            field=models.ManyToManyField(default=None, to='projects_app.Project'),
        ),
    ]
