# Generated by Django 3.1.5 on 2021-02-01 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210201_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='projects',
        ),
    ]
