# Generated by Django 3.1.5 on 2021-02-13 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_appuser_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
