# Generated by Django 3.1.5 on 2021-02-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210214_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/user.png', null=True, upload_to='profile_pics'),
        ),
    ]
