# Generated by Django 3.1.5 on 2021-01-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('description', models.TextField(blank=True, max_length=264)),
                ('colour', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('dueDate', models.DateField()),
                ('description', models.TextField(blank=True, max_length=264)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Close')], default='OP', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('comment', models.CharField(blank=True, max_length=264)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('CL', 'Close')], default='OP', max_length=2)),
                ('labels', models.ManyToManyField(to='issues_app.Label')),
                ('milestones', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='issues_app.milestone')),
            ],
        ),
    ]
