# Generated by Django 3.1.5 on 2021-01-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='milestones',
        ),
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='issues_app.Label'),
        ),
    ]
