# Generated by Django 3.1.5 on 2021-01-31 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_status'),
        ('issues_app', '0003_auto_20210129_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects_app.column'),
        ),
    ]
