# Generated by Django 3.1.5 on 2021-02-01 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appuser_projects'),
        ('projects_app', '0003_auto_20210131_1956'),
        ('issues_app', '0005_auto_20210131_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignees', to='users.appuser'),
        ),
        migrations.AddField(
            model_name='issue',
            name='milestones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='milestones', to='issues_app.milestone'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='column', to='projects_app.column'),
        ),
    ]
