# Generated by Django 3.1.5 on 2021-02-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appuser_projects'),
        ('issues_app', '0008_auto_20210201_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignees', to='users.AppUser'),
        ),
    ]
