# Generated by Django 3.1.5 on 2021-02-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_app', '0009_auto_20210201_2025'),
        ('issues_app', '0007_auto_20210201_2054'),
    ]

    operations = [
    ]
