# Generated by Django 3.1.5 on 2021-02-04 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0004_auto_20210204_1315'),
        ('issues_app', '0011_auto_20210204_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repositories_app.repository'),
        ),
        migrations.AlterField(
            model_name='label',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repositories_app.repository'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='repositories_app.repository'),
        ),
    ]
