# Generated by Django 3.1.5 on 2021-02-04 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_app', '0012_auto_20210204_1347'),
        ('issues_app', '0010_merge_20210204_0931'),
    ]

    operations = [
    ]
