# Generated by Django 3.1.5 on 2021-02-06 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_auto_20210131_1956'),
        ('issues_app', '0013_merge_20210204_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column', to='projects_app.column'),
        ),
    ]
