# Generated by Django 3.1.5 on 2021-02-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0004_project_repository'),
        ('issues_app', '0014_auto_20210206_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='projects_app.column'),
        ),
    ]
