# Generated by Django 3.1.5 on 2021-02-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0010_merge_20210208_1335'),
        ('issues_app', '0015_auto_20210206_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestone', to='issues_app.milestone'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories_app.repository'),
        ),
        migrations.AlterField(
            model_name='label',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories_app.repository'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repositories_app.repository'),
        ),
    ]
