# Generated by Django 3.1.5 on 2021-02-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appuser_projects'),
        ('repositories_app', '0010_merge_20210208_1335'),
        ('issues_app', '0017_auto_20210208_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='issues', to='users.AppUser'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issue', to='issues_app.milestone'),
        ),
        migrations.AlterField(
            model_name='label',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='repositories_app.repository'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='repository',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='repositories_app.repository'),
        ),
    ]
