# Generated by Django 3.1.5 on 2021-02-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues_app', '0018_auto_20210208_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='labels',
            field=models.ManyToManyField(blank=True, to='issues_app.Label'),
        ),
    ]
