# Generated by Django 3.1.5 on 2021-02-09 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_app', '0016_auto_20210209_0028'),
        ('issues_app', '0019_auto_20210208_1414'),
    ]

    operations = [
    ]
