# Generated by Django 3.1.5 on 2021-01-29 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wiki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=264)),
                ('content', models.TextField()),
                ('message', models.CharField(blank=True, max_length=264)),
                ('wiki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki_app.wiki')),
            ],
        ),
    ]
