# Generated by Django 3.1.5 on 2021-02-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0006_auto_20210204_2129'),
        ('wiki_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wiki',
            name='title',
        ),
        migrations.AddField(
            model_name='wiki',
            name='repository',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='wiki', to='repositories_app.repository'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='wiki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki_app.wiki'),
        ),
    ]
