# Generated by Django 3.1.5 on 2021-02-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki_app', '0002_auto_20210204_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='wiki',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='wiki_app.wiki'),
        ),
    ]
