# Generated by Django 3.1.5 on 2021-01-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0003_auto_20210131_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
