# Generated by Django 3.1.5 on 2021-01-31 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0004_auto_20210131_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commits', to='branches_app.branch'),
        ),
    ]
