# Generated by Django 3.1.5 on 2021-02-05 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0005_auto_20210131_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='parent_branch',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='date',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='description',
        ),
        migrations.RemoveField(
            model_name='commit',
            name='name',
        ),
    ]
