# Generated by Django 3.1.5 on 2021-02-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0006_auto_20210205_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='commit',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='commit',
            name='name',
            field=models.CharField(default=None, max_length=264),
        ),
    ]
