# Generated by Django 3.1.5 on 2021-02-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0013_auto_20210205_2150'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(fields=('name', 'repository'), name='unique_branch_name_in_repository'),
        ),
    ]
