# Generated by Django 3.1.5 on 2021-02-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0014_auto_20210205_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
