# Generated by Django 3.1.5 on 2021-02-06 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches_app', '0015_branch_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='parent_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches_app.branch'),
        ),
    ]
