# Generated by Django 3.1.5 on 2021-02-06 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repositories_app', '0008_auto_20210204_2326'),
        ('branches_app', '0017_auto_20210206_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositories_app.repository'),
        ),
    ]
