# Generated by Django 3.1.5 on 2021-02-06 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_appuser_projects'),
        ('branches_app', '0018_auto_20210206_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='commit',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.appuser'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='commit',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
